# Stylus section

#xsetwacom set "Wacom Intuos Pro M Pen stylus" Suppress 2
#xsetwacom set "Wacom Intuos Pro M Pen stylus" Threshold 27
#xsetwacom set "Wacom Intuos Pro M Pen stylus" PressureCurve 0 0 100 100
#xsetwacom set "Wacom Intuos Pro M Pen stylus" TabletPCButton on  # default for tablet PCs, it's off for tablets
#xsetwacom set "Wacom Intuos Pro M Pen stylus" Mode Absolute
#xsetwacom set "Wacom Intuos Pro M Pen stylus" Button 1 1
xsetwacom set "Wacom Intuos Pro M Pen stylus" Button 2 2
xsetwacom set "Wacom Intuos Pro M Pen stylus" Button 3 'key b'
#xsetwacom set "Wacom Intuos Pro M Pen stylus" Area 0 0 ?? ??

# Eraser section

#xsetwacom set "Wacom Intuos Pro M Pen eraser" Suppress 2
#xsetwacom set "Wacom Intuos Pro M Pen eraser" RawSample 4
#xsetwacom set "Wacom Intuos Pro M Pen eraser" Threshold 27
#xsetwacom set "Wacom Intuos Pro M Pen eraser" PressureCurve 0 0 100 100
#xsetwacom set "Wacom Intuos Pro M Pen eraser" Mode Absolute
#xsetwacom set "Wacom Intuos Pro M Pen eraser" Button 1 1
#xsetwacom set "Wacom Intuos Pro M Pen eraser" Area 0 0 ?? ??

# Cursor section

#xsetwacom set "Wacom Intuos Pro M Pen cursor" Suppress 2 
#xsetwacom set "Wacom Intuos Pro M Pen cursor" RawSample 4
#xsetwacom set "Wacom Intuos Pro M Pen cursor" CursorProximity 10  # default depends on tablet
#xsetwacom set "Wacom Intuos Pro M Pen cursor" Mode Relative
#xsetwacom set "Wacom Intuos Pro M Pen cursor" Button 1 1
#xsetwacom set "Wacom Intuos Pro M Pen cursor" Button 2 2
#xsetwacom set "Wacom Intuos Pro M Pen cursor" Button 3 3
#xsetwacom set "Wacom Intuos Pro M Pen cursor" Area 0 0 ?? ??

# Touch, single finger (1FGT) section

xsetwacom set "Wacom Intuos Pro M Finger touch" Touch off
#xsetwacom set "Wacom Intuos Pro M Finger touch" Suppress 2
#xsetwacom set "Wacom Intuos Pro M Finger touch" RawSample 4
#xsetwacom set "Wacom Intuos Pro M Finger touch" Threshold 27
#xsetwacom set "Wacom Intuos Pro M Finger touch" Mode Absolute
#xsetwacom set "Wacom Intuos Pro M Finger touch" TapTime 250
#xsetwacom set "Wacom Intuos Pro M Finger touch" Button 1 1
#xsetwacom set "Wacom Intuos Pro M Finger touch" Area 0 0 ?? ??

# Touch, two finger (2FGT) section

#xsetwacom set "Wacom Intuos Pro M Finger touch" Touch on
#xsetwacom set "Wacom Intuos Pro M Finger touch" Gesture on
#xsetwacom set "Wacom Intuos Pro M Finger touch" Suppress 2
#xsetwacom set "Wacom Intuos Pro M Finger touch" RawSample 4
#xsetwacom set "Wacom Intuos Pro M Finger touch" Threshold 27
#xsetwacom set "Wacom Intuos Pro M Finger touch" Mode Relative
#xsetwacom set "Wacom Intuos Pro M Finger touch" Button 1 1
#xsetwacom set "Wacom Intuos Pro M Finger touch" ZoomDistance 50
#xsetwacom set "Wacom Intuos Pro M Finger touch" ScrollDistance 20
#xsetwacom set "Wacom Intuos Pro M Finger touch" TapTime 250
#xsetwacom set "Wacom Intuos Pro M Finger touch" Area 0 0 ?? ??

# Buttons

#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 2 'key shift'
#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 3 'key ctrl'
#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 8 'key alt'
#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 9 'key esc'

xsetwacom set "Wacom Intuos Pro M Pad pad" AbsWheelUp 'key ='
xsetwacom set "Wacom Intuos Pro M Pad pad" Button 1 'key F12'
xsetwacom set "Wacom Intuos Pro M Pad pad" AbsWheelDown 'key -'

xsetwacom set "Wacom Intuos Pro M Pad pad" Button 10 'key z'
xsetwacom set "Wacom Intuos Pro M Pad pad" Button 11 'key b'
#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 12 'key 12'
#xsetwacom set "Wacom Intuos Pro M Pad pad" Button 13 'key F2'
